# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/workspace/batch-image-resizer/mainwidget.ui'
#
# Created: Thu Apr 05 15:10:16 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_mainWidget(object):
    def setupUi(self, mainWidget):
        mainWidget.setObjectName(_fromUtf8("mainWidget"))
        mainWidget.resize(567, 476)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        mainWidget.setFont(font)
        self.verticalLayout_4 = QtGui.QVBoxLayout(mainWidget)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.mainFrame = QtGui.QFrame(mainWidget)
        self.mainFrame.setStyleSheet(_fromUtf8("#mainFrame{\n"
"    /*background-color: rgb(214, 214, 214);\n"
"    border-image: url(:/images/metal-background.jpg);*/\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(226, 230, 231, 255), stop:1 rgba(196, 201, 204, 255));\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"#logoFrame{\n"
"/*background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(78, 78, 78, 78), stop:1 rgba(0, 0, 0, 78));*/\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(204, 208, 209, 255), stop:1 rgba(169, 174, 177, 255));\n"
"}\n"
"\n"
"#toolsFrame{\n"
"    /*background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(80, 80, 80, 255), stop:1 rgba(52, 52, 52, 255));*/\n"
"    min-height: 28px;\n"
"    max-height: 28px;\n"
"    margin-bottom: 2px;\n"
"    border: none;\n"
"    padding: 0px;\n"
"    border-image: url(:/images/bottom-line-bg.png) repeat bottom;\n"
"}\n"
"/*\n"
"#toolsFrame QPushButton{\n"
"     border-left: 1px solid #4C4C4C;\n"
"    border-right: 1px solid #000000;\n"
"     border-radius: 0px;\n"
"     min-height: 25px;\n"
"     padding: 0px 10px 0px 10px;\n"
"     color: #000000;\n"
"     margin: 0px;\n"
"    line-height: 25px;\n"
"}\n"
"toolsFrame QPushButton#addButton{\n"
"     /*border-left: 1px solid #000000;\n"
"}\n"
"\n"
"*/\n"
"#doButton:pressed {\n"
"     background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                       stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
" }\n"
"\n"
"#doButton:flat {\n"
"     border: none; \n"
" }\n"
"\n"
"#doButton:default {\n"
"     border-color: navy; \n"
" }\n"
"\n"
"#menuToolsFrame{\n"
"    /*background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(80, 80, 80, 255), stop:1 rgba(52, 52, 52, 255));*/\n"
"    min-height: 32px;\n"
"    max-height: 32px;\n"
"    padding: 0px;\n"
"    border: none;\n"
"    margin: 0px;\n"
"    background-image: url(:/images/menu-tools-bg.png);\n"
"}\n"
""))
        self.mainFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.mainFrame.setObjectName(_fromUtf8("mainFrame"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.mainFrame)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.logoFrame = QtGui.QFrame(self.mainFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logoFrame.sizePolicy().hasHeightForWidth())
        self.logoFrame.setSizePolicy(sizePolicy)
        self.logoFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.logoFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.logoFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.logoFrame.setObjectName(_fromUtf8("logoFrame"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.logoFrame)
        self.horizontalLayout_4.setSpacing(16)
        self.horizontalLayout_4.setContentsMargins(8, 5, 5, 4)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.companyLabel = QtGui.QLabel(self.logoFrame)
        self.companyLabel.setText(_fromUtf8(""))
        self.companyLabel.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/hibosoft_logo.png")))
        self.companyLabel.setObjectName(_fromUtf8("companyLabel"))
        self.horizontalLayout_4.addWidget(self.companyLabel)
        self.logoLabel = QtGui.QLabel(self.logoFrame)
        self.logoLabel.setText(_fromUtf8(""))
        self.logoLabel.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/batch-image-resizer-name.png")))
        self.logoLabel.setObjectName(_fromUtf8("logoLabel"))
        self.horizontalLayout_4.addWidget(self.logoLabel)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_3.addWidget(self.logoFrame)
        self.filesTableFrame = QtGui.QFrame(self.mainFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filesTableFrame.sizePolicy().hasHeightForWidth())
        self.filesTableFrame.setSizePolicy(sizePolicy)
        self.filesTableFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.filesTableFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.filesTableFrame.setObjectName(_fromUtf8("filesTableFrame"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.filesTableFrame)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.modeFrame = QtGui.QFrame(self.filesTableFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modeFrame.sizePolicy().hasHeightForWidth())
        self.modeFrame.setSizePolicy(sizePolicy)
        self.modeFrame.setStyleSheet(_fromUtf8(""))
        self.modeFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.modeFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.modeFrame.setLineWidth(0)
        self.modeFrame.setObjectName(_fromUtf8("modeFrame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.modeFrame)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.step1Label = QtGui.QLabel(self.modeFrame)
        self.step1Label.setText(_fromUtf8(""))
        self.step1Label.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/step1.png")))
        self.step1Label.setMargin(0)
        self.step1Label.setObjectName(_fromUtf8("step1Label"))
        self.horizontalLayout_3.addWidget(self.step1Label)
        self.modeComboBox = QtGui.QComboBox(self.modeFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modeComboBox.sizePolicy().hasHeightForWidth())
        self.modeComboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.modeComboBox.setFont(font)
        self.modeComboBox.setStyleSheet(_fromUtf8("margin-left:8px;"))
        self.modeComboBox.setObjectName(_fromUtf8("modeComboBox"))
        self.modeComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.modeComboBox)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addWidget(self.modeFrame)
        self.filesTable = MyTreeWidget(self.filesTableFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(181)
        sizePolicy.setHeightForWidth(self.filesTable.sizePolicy().hasHeightForWidth())
        self.filesTable.setSizePolicy(sizePolicy)
        self.filesTable.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(13)
        self.filesTable.setFont(font)
        self.filesTable.setAutoFillBackground(True)
        self.filesTable.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.filesTable.setAutoScrollMargin(30)
        self.filesTable.setDragEnabled(False)
        self.filesTable.setDragDropOverwriteMode(True)
        self.filesTable.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.filesTable.setAlternatingRowColors(True)
        self.filesTable.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.filesTable.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.filesTable.setUniformRowHeights(True)
        self.filesTable.setItemsExpandable(False)
        self.filesTable.setExpandsOnDoubleClick(False)
        self.filesTable.setObjectName(_fromUtf8("filesTable"))
        self.verticalLayout_2.addWidget(self.filesTable)
        self.toolsFrame = QtGui.QFrame(self.filesTableFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolsFrame.sizePolicy().hasHeightForWidth())
        self.toolsFrame.setSizePolicy(sizePolicy)
        self.toolsFrame.setStyleSheet(_fromUtf8(""))
        self.toolsFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.toolsFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.toolsFrame.setLineWidth(0)
        self.toolsFrame.setObjectName(_fromUtf8("toolsFrame"))
        self.verticalLayout = QtGui.QVBoxLayout(self.toolsFrame)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.infoLabel = QtGui.QLabel(self.toolsFrame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.infoLabel.setFont(font)
        self.infoLabel.setObjectName(_fromUtf8("infoLabel"))
        self.horizontalLayout_2.addWidget(self.infoLabel)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.addFilesButton = QtGui.QToolButton(self.toolsFrame)
        self.addFilesButton.setEnabled(True)
        self.addFilesButton.setMinimumSize(QtCore.QSize(0, 25))
        self.addFilesButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/add_image.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addFilesButton.setIcon(icon)
        self.addFilesButton.setIconSize(QtCore.QSize(24, 24))
        self.addFilesButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.addFilesButton.setAutoRaise(True)
        self.addFilesButton.setObjectName(_fromUtf8("addFilesButton"))
        self.horizontalLayout_2.addWidget(self.addFilesButton)
        self.addFolderButton = QtGui.QToolButton(self.toolsFrame)
        self.addFolderButton.setEnabled(True)
        self.addFolderButton.setMinimumSize(QtCore.QSize(0, 25))
        self.addFolderButton.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/add_folder.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addFolderButton.setIcon(icon1)
        self.addFolderButton.setIconSize(QtCore.QSize(24, 24))
        self.addFolderButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.addFolderButton.setAutoRaise(True)
        self.addFolderButton.setObjectName(_fromUtf8("addFolderButton"))
        self.horizontalLayout_2.addWidget(self.addFolderButton)
        self.deleteButton = QtGui.QToolButton(self.toolsFrame)
        self.deleteButton.setEnabled(True)
        self.deleteButton.setMinimumSize(QtCore.QSize(0, 25))
        self.deleteButton.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/trashcan-delete3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteButton.setIcon(icon2)
        self.deleteButton.setIconSize(QtCore.QSize(24, 24))
        self.deleteButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.deleteButton.setAutoRaise(True)
        self.deleteButton.setObjectName(_fromUtf8("deleteButton"))
        self.horizontalLayout_2.addWidget(self.deleteButton)
        self.clearButton = QtGui.QToolButton(self.toolsFrame)
        self.clearButton.setEnabled(True)
        self.clearButton.setMinimumSize(QtCore.QSize(0, 25))
        self.clearButton.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/clear.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clearButton.setIcon(icon3)
        self.clearButton.setIconSize(QtCore.QSize(24, 24))
        self.clearButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.clearButton.setAutoRaise(True)
        self.clearButton.setObjectName(_fromUtf8("clearButton"))
        self.horizontalLayout_2.addWidget(self.clearButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addWidget(self.toolsFrame)
        self.verticalLayout_3.addWidget(self.filesTableFrame)
        self.outputFrame = QtGui.QFrame(self.mainFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputFrame.sizePolicy().hasHeightForWidth())
        self.outputFrame.setSizePolicy(sizePolicy)
        self.outputFrame.setStyleSheet(_fromUtf8(""))
        self.outputFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.outputFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.outputFrame.setObjectName(_fromUtf8("outputFrame"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.outputFrame)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setContentsMargins(9, 0, 0, 0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.outputSettingFrame = QtGui.QFrame(self.outputFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputSettingFrame.sizePolicy().hasHeightForWidth())
        self.outputSettingFrame.setSizePolicy(sizePolicy)
        self.outputSettingFrame.setObjectName(_fromUtf8("outputSettingFrame"))
        self.gridLayout = QtGui.QGridLayout(self.outputSettingFrame)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.outputLabel = QtGui.QLabel(self.outputSettingFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputLabel.sizePolicy().hasHeightForWidth())
        self.outputLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.outputLabel.setFont(font)
        self.outputLabel.setObjectName(_fromUtf8("outputLabel"))
        self.gridLayout.addWidget(self.outputLabel, 1, 0, 1, 1)
        self.openOutputCheckBox = QtGui.QCheckBox(self.outputSettingFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openOutputCheckBox.sizePolicy().hasHeightForWidth())
        self.openOutputCheckBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.openOutputCheckBox.setFont(font)
        self.openOutputCheckBox.setChecked(True)
        self.openOutputCheckBox.setObjectName(_fromUtf8("openOutputCheckBox"))
        self.gridLayout.addWidget(self.openOutputCheckBox, 0, 0, 1, 2)
        self.openOutputButton = QtGui.QToolButton(self.outputSettingFrame)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openOutputButton.setIcon(icon4)
        self.openOutputButton.setAutoRaise(True)
        self.openOutputButton.setObjectName(_fromUtf8("openOutputButton"))
        self.gridLayout.addWidget(self.openOutputButton, 1, 2, 1, 1)
        self.outputComboBox = QtGui.QComboBox(self.outputSettingFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputComboBox.sizePolicy().hasHeightForWidth())
        self.outputComboBox.setSizePolicy(sizePolicy)
        self.outputComboBox.setObjectName(_fromUtf8("outputComboBox"))
        self.gridLayout.addWidget(self.outputComboBox, 1, 1, 1, 1)
        self.horizontalLayout_5.addWidget(self.outputSettingFrame)
        self.startFrame = QtGui.QFrame(self.outputFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startFrame.sizePolicy().hasHeightForWidth())
        self.startFrame.setSizePolicy(sizePolicy)
        self.startFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.startFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.startFrame.setObjectName(_fromUtf8("startFrame"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.startFrame)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.doButton = QtGui.QPushButton(self.startFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doButton.sizePolicy().hasHeightForWidth())
        self.doButton.setSizePolicy(sizePolicy)
        self.doButton.setMinimumSize(QtCore.QSize(130, 0))
        self.doButton.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.doButton.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/coffee.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.doButton.setIcon(icon5)
        self.doButton.setIconSize(QtCore.QSize(32, 32))
        self.doButton.setDefault(True)
        self.doButton.setFlat(False)
        self.doButton.setObjectName(_fromUtf8("doButton"))
        self.verticalLayout_5.addWidget(self.doButton)
        self.horizontalLayout_5.addWidget(self.startFrame)
        self.verticalLayout_3.addWidget(self.outputFrame)
        self.menuToolsFrame = QtGui.QFrame(self.mainFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuToolsFrame.sizePolicy().hasHeightForWidth())
        self.menuToolsFrame.setSizePolicy(sizePolicy)
        self.menuToolsFrame.setMinimumSize(QtCore.QSize(0, 32))
        self.menuToolsFrame.setMaximumSize(QtCore.QSize(16777214, 32))
        self.menuToolsFrame.setStyleSheet(_fromUtf8(""))
        self.menuToolsFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.menuToolsFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.menuToolsFrame.setObjectName(_fromUtf8("menuToolsFrame"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.menuToolsFrame)
        self.horizontalLayout_6.setSpacing(1)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.helpButton = QtGui.QToolButton(self.menuToolsFrame)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/help_button.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.helpButton.setIcon(icon6)
        self.helpButton.setAutoRaise(True)
        self.helpButton.setObjectName(_fromUtf8("helpButton"))
        self.horizontalLayout_6.addWidget(self.helpButton)
        self.registerButton = QtGui.QToolButton(self.menuToolsFrame)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/key.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.registerButton.setIcon(icon7)
        self.registerButton.setAutoRaise(True)
        self.registerButton.setObjectName(_fromUtf8("registerButton"))
        self.horizontalLayout_6.addWidget(self.registerButton)
        self.aboutButton = QtGui.QToolButton(self.menuToolsFrame)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/info.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aboutButton.setIcon(icon8)
        self.aboutButton.setAutoRaise(True)
        self.aboutButton.setObjectName(_fromUtf8("aboutButton"))
        self.horizontalLayout_6.addWidget(self.aboutButton)
        self.settingsButton = QtGui.QToolButton(self.menuToolsFrame)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/setting.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsButton.setIcon(icon9)
        self.settingsButton.setAutoRaise(True)
        self.settingsButton.setObjectName(_fromUtf8("settingsButton"))
        self.horizontalLayout_6.addWidget(self.settingsButton)
        self.quitButton = QtGui.QToolButton(self.menuToolsFrame)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.quitButton.setIcon(icon10)
        self.quitButton.setAutoRaise(True)
        self.quitButton.setObjectName(_fromUtf8("quitButton"))
        self.horizontalLayout_6.addWidget(self.quitButton)
        spacerItem4 = QtGui.QSpacerItem(228, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout_3.addWidget(self.menuToolsFrame)
        self.verticalLayout_4.addWidget(self.mainFrame)

        self.retranslateUi(mainWidget)
        QtCore.QMetaObject.connectSlotsByName(mainWidget)
        mainWidget.setTabOrder(self.modeComboBox, self.addFilesButton)
        mainWidget.setTabOrder(self.addFilesButton, self.addFolderButton)
        mainWidget.setTabOrder(self.addFolderButton, self.deleteButton)
        mainWidget.setTabOrder(self.deleteButton, self.clearButton)
        mainWidget.setTabOrder(self.clearButton, self.openOutputCheckBox)
        mainWidget.setTabOrder(self.openOutputCheckBox, self.outputComboBox)
        mainWidget.setTabOrder(self.outputComboBox, self.openOutputButton)
        mainWidget.setTabOrder(self.openOutputButton, self.helpButton)
        mainWidget.setTabOrder(self.helpButton, self.registerButton)
        mainWidget.setTabOrder(self.registerButton, self.aboutButton)
        mainWidget.setTabOrder(self.aboutButton, self.settingsButton)
        mainWidget.setTabOrder(self.settingsButton, self.quitButton)
        mainWidget.setTabOrder(self.quitButton, self.doButton)
        mainWidget.setTabOrder(self.doButton, self.filesTable)

    def retranslateUi(self, mainWidget):
        mainWidget.setWindowTitle(QtGui.QApplication.translate("mainWidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.modeComboBox.setItemText(0, QtGui.QApplication.translate("mainWidget", "Please Select File Type Here ...", None, QtGui.QApplication.UnicodeUTF8))
        self.filesTable.headerItem().setText(0, QtGui.QApplication.translate("mainWidget", "Files", None, QtGui.QApplication.UnicodeUTF8))
        self.infoLabel.setText(QtGui.QApplication.translate("mainWidget", "tips here", None, QtGui.QApplication.UnicodeUTF8))
        self.addFilesButton.setToolTip(QtGui.QApplication.translate("mainWidget", "Add image files", None, QtGui.QApplication.UnicodeUTF8))
        self.addFolderButton.setToolTip(QtGui.QApplication.translate("mainWidget", "Add an image folder", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteButton.setToolTip(QtGui.QApplication.translate("mainWidget", "Delete selected items", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setToolTip(QtGui.QApplication.translate("mainWidget", "Clear table", None, QtGui.QApplication.UnicodeUTF8))
        self.outputLabel.setText(QtGui.QApplication.translate("mainWidget", "Output:", None, QtGui.QApplication.UnicodeUTF8))
        self.openOutputCheckBox.setText(QtGui.QApplication.translate("mainWidget", "Open output folder after processing is complete.", None, QtGui.QApplication.UnicodeUTF8))
        self.openOutputButton.setToolTip(QtGui.QApplication.translate("mainWidget", "Open output folder", None, QtGui.QApplication.UnicodeUTF8))
        self.openOutputButton.setText(QtGui.QApplication.translate("mainWidget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.doButton.setToolTip(QtGui.QApplication.translate("mainWidget", "Enjoy a cup of coffee,let us do the hard work for you.", None, QtGui.QApplication.UnicodeUTF8))
        self.doButton.setText(QtGui.QApplication.translate("mainWidget", "Start Resize", None, QtGui.QApplication.UnicodeUTF8))
        self.helpButton.setToolTip(QtGui.QApplication.translate("mainWidget", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.helpButton.setText(QtGui.QApplication.translate("mainWidget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.registerButton.setToolTip(QtGui.QApplication.translate("mainWidget", "Registration", None, QtGui.QApplication.UnicodeUTF8))
        self.registerButton.setText(QtGui.QApplication.translate("mainWidget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.aboutButton.setToolTip(QtGui.QApplication.translate("mainWidget", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.aboutButton.setText(QtGui.QApplication.translate("mainWidget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.settingsButton.setToolTip(QtGui.QApplication.translate("mainWidget", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.settingsButton.setText(QtGui.QApplication.translate("mainWidget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.quitButton.setToolTip(QtGui.QApplication.translate("mainWidget", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.quitButton.setText(QtGui.QApplication.translate("mainWidget", "...", None, QtGui.QApplication.UnicodeUTF8))

from mytreewidget import MyTreeWidget
import prog_rc
