# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:/workspace/batch-image-resizer/settingswidget.ui'
#
# Created: Mon Feb 10 12:43:09 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_settingsDialog(object):
    def setupUi(self, settingsDialog):
        settingsDialog.setObjectName(_fromUtf8("settingsDialog"))
        settingsDialog.resize(373, 341)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        settingsDialog.setFont(font)
        self.horizontalLayout_3 = QtGui.QHBoxLayout(settingsDialog)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.mainFrame = QtGui.QFrame(settingsDialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial,Helvetica,sans-serif"))
        self.mainFrame.setFont(font)
        self.mainFrame.setStyleSheet(_fromUtf8("#mainFrame{\n"
"    /*background-color: rgb(214, 214, 214);\n"
"    border-image: url(:/images/metal-background.jpg);*/\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(226, 230, 231, 255), stop:1 rgba(196, 201, 204, 255));\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"    font-family:Arial,Helvetica,sans-serif;\n"
"}\n"
"\n"
"\n"
""))
        self.mainFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.mainFrame.setLineWidth(5)
        self.mainFrame.setObjectName(_fromUtf8("mainFrame"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.mainFrame)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setContentsMargins(12, -1, 12, -1)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.generalLabel = QtGui.QLabel(self.mainFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generalLabel.sizePolicy().hasHeightForWidth())
        self.generalLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.generalLabel.setFont(font)
        self.generalLabel.setObjectName(_fromUtf8("generalLabel"))
        self.verticalLayout_4.addWidget(self.generalLabel)
        self.generalFrame = QtGui.QFrame(self.mainFrame)
        self.generalFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.generalFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.generalFrame.setObjectName(_fromUtf8("generalFrame"))
        self.gridLayout = QtGui.QGridLayout(self.generalFrame)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.sizeModeLabel = QtGui.QLabel(self.generalFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizeModeLabel.sizePolicy().hasHeightForWidth())
        self.sizeModeLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.sizeModeLabel.setFont(font)
        self.sizeModeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sizeModeLabel.setObjectName(_fromUtf8("sizeModeLabel"))
        self.gridLayout.addWidget(self.sizeModeLabel, 0, 0, 1, 1)
        self.sizeModeComboBox = QtGui.QComboBox(self.generalFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizeModeComboBox.sizePolicy().hasHeightForWidth())
        self.sizeModeComboBox.setSizePolicy(sizePolicy)
        self.sizeModeComboBox.setObjectName(_fromUtf8("sizeModeComboBox"))
        self.gridLayout.addWidget(self.sizeModeComboBox, 0, 1, 1, 2)
        self.widthModeLabel_2 = QtGui.QLabel(self.generalFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widthModeLabel_2.sizePolicy().hasHeightForWidth())
        self.widthModeLabel_2.setSizePolicy(sizePolicy)
        self.widthModeLabel_2.setMinimumSize(QtCore.QSize(20, 0))
        self.widthModeLabel_2.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.widthModeLabel_2.setFont(font)
        self.widthModeLabel_2.setText(_fromUtf8(""))
        self.widthModeLabel_2.setObjectName(_fromUtf8("widthModeLabel_2"))
        self.gridLayout.addWidget(self.widthModeLabel_2, 0, 3, 1, 1)
        self.widthLabel = QtGui.QLabel(self.generalFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widthLabel.sizePolicy().hasHeightForWidth())
        self.widthLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.widthLabel.setFont(font)
        self.widthLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.widthLabel.setObjectName(_fromUtf8("widthLabel"))
        self.gridLayout.addWidget(self.widthLabel, 1, 0, 1, 1)
        self.widthSpinBox = QtGui.QSpinBox(self.generalFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widthSpinBox.sizePolicy().hasHeightForWidth())
        self.widthSpinBox.setSizePolicy(sizePolicy)
        self.widthSpinBox.setObjectName(_fromUtf8("widthSpinBox"))
        self.gridLayout.addWidget(self.widthSpinBox, 1, 1, 1, 1)
        self.widthModeLabel = QtGui.QLabel(self.generalFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widthModeLabel.sizePolicy().hasHeightForWidth())
        self.widthModeLabel.setSizePolicy(sizePolicy)
        self.widthModeLabel.setMinimumSize(QtCore.QSize(20, 0))
        self.widthModeLabel.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.widthModeLabel.setFont(font)
        self.widthModeLabel.setObjectName(_fromUtf8("widthModeLabel"))
        self.gridLayout.addWidget(self.widthModeLabel, 1, 2, 1, 1)
        self.ratioLabel = QtGui.QLabel(self.generalFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ratioLabel.sizePolicy().hasHeightForWidth())
        self.ratioLabel.setSizePolicy(sizePolicy)
        self.ratioLabel.setMinimumSize(QtCore.QSize(20, 0))
        self.ratioLabel.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.ratioLabel.setFont(font)
        self.ratioLabel.setText(_fromUtf8(""))
        self.ratioLabel.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/ratio.png")))
        self.ratioLabel.setObjectName(_fromUtf8("ratioLabel"))
        self.gridLayout.addWidget(self.ratioLabel, 1, 3, 2, 1)
        self.heightLabel = QtGui.QLabel(self.generalFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heightLabel.sizePolicy().hasHeightForWidth())
        self.heightLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.heightLabel.setFont(font)
        self.heightLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.heightLabel.setObjectName(_fromUtf8("heightLabel"))
        self.gridLayout.addWidget(self.heightLabel, 2, 0, 1, 1)
        self.heightSpinBox = QtGui.QSpinBox(self.generalFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heightSpinBox.sizePolicy().hasHeightForWidth())
        self.heightSpinBox.setSizePolicy(sizePolicy)
        self.heightSpinBox.setObjectName(_fromUtf8("heightSpinBox"))
        self.gridLayout.addWidget(self.heightSpinBox, 2, 1, 1, 1)
        self.heightModeLabel = QtGui.QLabel(self.generalFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heightModeLabel.sizePolicy().hasHeightForWidth())
        self.heightModeLabel.setSizePolicy(sizePolicy)
        self.heightModeLabel.setMinimumSize(QtCore.QSize(20, 0))
        self.heightModeLabel.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.heightModeLabel.setFont(font)
        self.heightModeLabel.setObjectName(_fromUtf8("heightModeLabel"))
        self.gridLayout.addWidget(self.heightModeLabel, 2, 2, 1, 1)
        self.formatLabel = QtGui.QLabel(self.generalFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.formatLabel.sizePolicy().hasHeightForWidth())
        self.formatLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.formatLabel.setFont(font)
        self.formatLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formatLabel.setObjectName(_fromUtf8("formatLabel"))
        self.gridLayout.addWidget(self.formatLabel, 3, 0, 1, 1)
        self.outputFormatComboBox = QtGui.QComboBox(self.generalFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputFormatComboBox.sizePolicy().hasHeightForWidth())
        self.outputFormatComboBox.setSizePolicy(sizePolicy)
        self.outputFormatComboBox.setObjectName(_fromUtf8("outputFormatComboBox"))
        self.gridLayout.addWidget(self.outputFormatComboBox, 3, 1, 1, 2)
        self.heightModeLabel_2 = QtGui.QLabel(self.generalFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heightModeLabel_2.sizePolicy().hasHeightForWidth())
        self.heightModeLabel_2.setSizePolicy(sizePolicy)
        self.heightModeLabel_2.setMinimumSize(QtCore.QSize(20, 0))
        self.heightModeLabel_2.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.heightModeLabel_2.setFont(font)
        self.heightModeLabel_2.setText(_fromUtf8(""))
        self.heightModeLabel_2.setObjectName(_fromUtf8("heightModeLabel_2"))
        self.gridLayout.addWidget(self.heightModeLabel_2, 3, 3, 1, 1)
        self.verticalLayout_4.addWidget(self.generalFrame)
        self.sep1 = QtGui.QLabel(self.mainFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sep1.sizePolicy().hasHeightForWidth())
        self.sep1.setSizePolicy(sizePolicy)
        self.sep1.setMinimumSize(QtCore.QSize(0, 2))
        self.sep1.setMaximumSize(QtCore.QSize(16777215, 2))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        self.sep1.setFont(font)
        self.sep1.setText(_fromUtf8(""))
        self.sep1.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/line-bg.png")))
        self.sep1.setScaledContents(True)
        self.sep1.setObjectName(_fromUtf8("sep1"))
        self.verticalLayout_4.addWidget(self.sep1)
        self.advancedLabel = QtGui.QLabel(self.mainFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.advancedLabel.sizePolicy().hasHeightForWidth())
        self.advancedLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.advancedLabel.setFont(font)
        self.advancedLabel.setObjectName(_fromUtf8("advancedLabel"))
        self.verticalLayout_4.addWidget(self.advancedLabel)
        self.advancedFrame = QtGui.QFrame(self.mainFrame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.advancedFrame.setFont(font)
        self.advancedFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.advancedFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.advancedFrame.setObjectName(_fromUtf8("advancedFrame"))
        self.verticalLayout = QtGui.QVBoxLayout(self.advancedFrame)
        self.verticalLayout.setSpacing(9)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.keepDateTimeCheckBox = QtGui.QCheckBox(self.advancedFrame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.keepDateTimeCheckBox.setFont(font)
        self.keepDateTimeCheckBox.setObjectName(_fromUtf8("keepDateTimeCheckBox"))
        self.verticalLayout.addWidget(self.keepDateTimeCheckBox)
        self.overwriteFilesCheckBox = QtGui.QCheckBox(self.advancedFrame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.overwriteFilesCheckBox.setFont(font)
        self.overwriteFilesCheckBox.setObjectName(_fromUtf8("overwriteFilesCheckBox"))
        self.verticalLayout.addWidget(self.overwriteFilesCheckBox)
        self.playSoundCheckBox = QtGui.QCheckBox(self.advancedFrame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.playSoundCheckBox.setFont(font)
        self.playSoundCheckBox.setObjectName(_fromUtf8("playSoundCheckBox"))
        self.verticalLayout.addWidget(self.playSoundCheckBox)
        self.verticalLayout_4.addWidget(self.advancedFrame)
        self.sep2 = QtGui.QLabel(self.mainFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sep2.sizePolicy().hasHeightForWidth())
        self.sep2.setSizePolicy(sizePolicy)
        self.sep2.setMinimumSize(QtCore.QSize(0, 2))
        self.sep2.setMaximumSize(QtCore.QSize(16777215, 2))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        self.sep2.setFont(font)
        self.sep2.setText(_fromUtf8(""))
        self.sep2.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/line-bg.png")))
        self.sep2.setScaledContents(True)
        self.sep2.setObjectName(_fromUtf8("sep2"))
        self.verticalLayout_4.addWidget(self.sep2)
        self.buttonsFrame = QtGui.QFrame(self.mainFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonsFrame.sizePolicy().hasHeightForWidth())
        self.buttonsFrame.setSizePolicy(sizePolicy)
        self.buttonsFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.buttonsFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.buttonsFrame.setObjectName(_fromUtf8("buttonsFrame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.buttonsFrame)
        self.horizontalLayout.setContentsMargins(-1, 4, -1, 4)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(71, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.startButton = QtGui.QPushButton(self.buttonsFrame)
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.horizontalLayout.addWidget(self.startButton)
        self.okButton = QtGui.QPushButton(self.buttonsFrame)
        self.okButton.setObjectName(_fromUtf8("okButton"))
        self.horizontalLayout.addWidget(self.okButton)
        self.cancelButton = QtGui.QPushButton(self.buttonsFrame)
        self.cancelButton.setObjectName(_fromUtf8("cancelButton"))
        self.horizontalLayout.addWidget(self.cancelButton)
        spacerItem1 = QtGui.QSpacerItem(71, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_4.addWidget(self.buttonsFrame)
        self.horizontalLayout_3.addWidget(self.mainFrame)

        self.retranslateUi(settingsDialog)
        QtCore.QObject.connect(self.cancelButton, QtCore.SIGNAL(_fromUtf8("clicked()")), settingsDialog.close)
        QtCore.QMetaObject.connectSlotsByName(settingsDialog)

    def retranslateUi(self, settingsDialog):
        settingsDialog.setWindowTitle(QtGui.QApplication.translate("settingsDialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.generalLabel.setText(QtGui.QApplication.translate("settingsDialog", "General:", None, QtGui.QApplication.UnicodeUTF8))
        self.sizeModeLabel.setText(QtGui.QApplication.translate("settingsDialog", "Size Mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.widthLabel.setText(QtGui.QApplication.translate("settingsDialog", "Width:", None, QtGui.QApplication.UnicodeUTF8))
        self.widthModeLabel.setText(QtGui.QApplication.translate("settingsDialog", "px", None, QtGui.QApplication.UnicodeUTF8))
        self.heightLabel.setText(QtGui.QApplication.translate("settingsDialog", "Height:", None, QtGui.QApplication.UnicodeUTF8))
        self.heightModeLabel.setText(QtGui.QApplication.translate("settingsDialog", "px", None, QtGui.QApplication.UnicodeUTF8))
        self.formatLabel.setText(QtGui.QApplication.translate("settingsDialog", "Out Format:", None, QtGui.QApplication.UnicodeUTF8))
        self.advancedLabel.setText(QtGui.QApplication.translate("settingsDialog", "Advanced:", None, QtGui.QApplication.UnicodeUTF8))
        self.keepDateTimeCheckBox.setText(QtGui.QApplication.translate("settingsDialog", "Keep original date/time attributes.", None, QtGui.QApplication.UnicodeUTF8))
        self.overwriteFilesCheckBox.setText(QtGui.QApplication.translate("settingsDialog", "Overwrite existing files in destination folder", None, QtGui.QApplication.UnicodeUTF8))
        self.playSoundCheckBox.setText(QtGui.QApplication.translate("settingsDialog", "Play sound when processing is complete", None, QtGui.QApplication.UnicodeUTF8))
        self.startButton.setText(QtGui.QApplication.translate("settingsDialog", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setText(QtGui.QApplication.translate("settingsDialog", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("settingsDialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

import prog_rc
